pipeline {
    agent any

    environment {
        AWS_EC2_IP = "13.218.215.189"
        SSH_USER = "ubuntu"
        JAR_NAME = "test-springboot-application-0.0.1-SNAPSHOT.jar"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/pranav-8660/test-springbootapp-jenkins.git'
            }
        }

        stage('Build with Maven') {
            steps {
                dir('test-springboot-application') { 
                    sh 'mvn clean package'
                }
            }
        }


        stage('Deploy to EC2') {
            steps {
                script {
                    sh """
                    cd test-springboot-application
                    
                    scp -o StrictHostKeyChecking=no -i /home/jenkins/keys/insta-test.pem target/${JAR_NAME} ubuntu@${AWS_EC2_IP}:/home/ubuntu/
                
                    ssh -o StrictHostKeyChecking=no -i /home/jenkins/keys/insta-test.pem ubuntu@${AWS_EC2_IP} <<EOF
                    pkill -f ${JAR_NAME} || true
                    nohup java -jar /home/ubuntu/${JAR_NAME} > /home/ubuntu/app.log 2>&1 &
                    exit
                EOF
                    """
                }

            }
        }
    }
}
